import type { Metadata } from "next";
import { Playfair_Display, Pacifico, Lato } from "next/font/google";
import "./globals.css";

const playFair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playFairD",
});

const pacifico = Pacifico({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--font-pacifico",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${playFair.variable} ${pacifico.variable} ${lato.variable} antialiased`}>
        <main className="container mx-auto py-5">
          {children}
        </main>
      </body>
    </html>
  );
}
